name: Elixir Test CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: "*/15 * * * *"

jobs:
  build:

    name: Build and test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Elixir
      uses: erlef/setup-elixir@885971a72ed1f9240973bd92ab57af8c1aa68f24
      with:
        elixir-version: '1.10.3'
        otp-version: '22.3' 
    - name: Restore dependencies cache
      uses: actions/cache@v2
      with:
        path: deps
        key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
        restore-keys: ${{ runner.os }}-mix-
    - name: Install dependencies
      run: | 
        elixirc test/tools/util.ex 
        mix deps.get
    - name: Start Server
      run: |
        docker pull selenium/standalone-chrome
        docker run -d -p  4444:4444 -v /dev/shm:/dev/shm selenium/standalone-chrome
    - name: Run Tests
      run: mix test